### PR TITLE
Update copyright notices to 2017 [ci skip]

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by oliverklee** [comment]
I think we can change this to 2017 now. :-)

**Comment by Atul9** [comment]
@oliverklee Are we going to merge it if I update the year to 2017 ?

**Comment by amatsuda** [comment]
@Atul9 I will.

**Comment by Atul9** [comment]
@amatsuda @oliverklee I have updated the PR please check.

**Comment by amatsuda** [comment]
@Atul9 Can you rebase -i and squash your commits into one and push -f please?
We don't want to see 3 commits just for doing this.

**Comment by oliverklee** [comment]
@amatsuda GitHub now has a new feature that allows squashing on merge so the contributor does not need to do this. :-)

https://github.com/blog/2141-squash-your-commits

**Comment by Atul9** [comment]
@amatsuda @oliverklee Its done.

**Comment by amatsuda** [comment]
@Atul9 Thank you!
@oliverklee Thank you, but I hate that feature.

**Pull request merged**
